
/*******************************************************************************
* generated by lcd-image-converter rev.c6da9ce from 2018-02-11 00:03:45 +0500
* image
* filename: unsaved
* name: Image
*
* preset name: sumotoy_font
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Edge 144
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_Image[13] = {
    
    0x00, 0x1f, 0xe0, 0x01, 0x7a, 0x50, 0x90, 0xa5, 0xc8, 0x02, 0x7f, 0x00, 0x00
};
const tImage Image = { image_data_Image, 10, 10,
    8 };

